PUT http://localhost:8080/notepads/3
Content-Type: application/json

{
  "title": "Título alterado",
  "subtitle": "As experiências acumuladas demonstram",
  "content": "As experiências acumuladas demonstram que a crescente influência da mídia desafia a capacidade de equalização do sistema de formação.",
  "created_at": "2023-04-17T10:48:18.584Z"
}